### ISSUE TITLE
Increase test coverage for Dashboard feature and refactoring

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-sli-service#78]
The dynatrace-sli-service got new features in regard to extracting SLO/SLI from a Dynatrace Dashboard. 
Please see: https://github.com/keptn-contrib/dynatrace-sli-service/pull/62

Increase the robustness of the new features.

**Task**
- Review of the new feature
- Add unit tests when required

**Chore tasks:**
- [ ] The dashboard feature creates SLO/SLI without `spec_version`. Set the spec_version to: `0.1.4`
- [ ] Even though there is no `dynatrace/dynatrace.conf.yaml` the service logs: 
```
020-09-17T08:39:00.243879384Z {"timestamp":"2020-09-17T08:39:00.243634332Z","logLevel":"DEBUG","message":"Found dynatrace/dynatrace.conf.yaml on service level"} 
  but no conf.yaml available
```
- [ ] Refactoring: func (ph *Handler) BuildDynatraceMetricsQuery(metricquery string, startUnix time.Time, endUnix time.Time, customFilters []*keptn.SLIFilter) (string, string) --> the property `customFilters` is obsolete

**Comment by agrimmer** [comment]
We should create a test case where a dashboard specifies a non-existing project/stage/service.
